"Redline Smalltalk, Copyright (c) James C. Ladd. All rights reserved. See LICENSE in the root of this distribution."

SequenceableCollection subclass: #Interval.

"category: instance creation"

- from: startInteger to: stopInteger
    "Answer an instance of class Interval, starting with the number startInteger, ending with the number stopInteger,
     and using the increment 1 to compute each successive element."
    self notImplementedYet.

- from: startInteger to: stopInteger by: stepInteger
    "Answer an instance of Interval, starting with the number startInteger, ending with the number stopInteger, and
     using the increment stepInteger to compute each successive element."
    self notImplementedYet.
