" Redline Smalltalk, Copyright (c) James C. Ladd. All rights reserved. See LICENSE in the root of this distribution "

Object < #BlockClosure

- value
     "Activate the receiver, a closure activation."
     <primitive: 201>

- value: firstArg
    "Activate the receiver, a closure activation."
    <primitive: 202>

- value: firstArg value: secondArg
    "Activate the receiver, a closure activation."
    <primitive: 203>

- value: firstArg value: secondArg value: thirdArg
    "Activate the receiver, a closure activation."
    <primitive: 204>

- value: firstArg value: secondArg value: thirdArg value: forthArg
    "Activate the receiver, a closure activation."
    <primitive: 205>

