/* Redline Smalltalk, Copyright (c) James C. Ladd. All rights reserved. See LICENSE in the root of this distribution */
package st.redline.compiler;

// This is a synthetic node, not generated by Parser.
public class Cascade {

    void begin(NodeVisitor nodeVisitor) {
        nodeVisitor.visitBegin(this);
    }

    void end(NodeVisitor nodeVisitor) {
        nodeVisitor.visitEnd(this);
    }
}
