"Redline Smalltalk, Copyright (c) James C. Ladd. All rights reserved. See LICENSE in the root of this distribution."

SequenceableCollection subclass: #LinkedList.

"category: instance creation"

- nextLink: aLink
    "Create an instance of Link that references the argument, aLink."
    self notImplementedYet.

"category: accessing"

- nextLink
    "Answer the receiver's reference."
    self notImplementedYet.

- nextLink: aLink
    "Set the receiver's reference to be the argument, aLink."
    self notImplementedYet.

"category: adding"

- addFirst: aLink
    "Add aLink to the beginning of the receiver's list. Answer aLink."
    self notImplementedYet.

- addLast: aLink
    "Add aLink to the end of the receiver's list. Answer aLink."
    self notImplementedYet.

"category: removing"

- removeFirst
    "Remove the receiver's first element and answer it. If the receiver is empty, report an error."
    self notImplementedYet.

- removeLast
    "Remove the receiver's last element and answer it. If the receiver is empty, report an error."
    self notImplementedYet.
