"Redline Smalltalk, Copyright (c) James C. Ladd. All rights reserved. See LICENSE in the root of this distribution."

Object subclass: #Magnitude.

"category: comparing"

- < aMagnitude
    "Answer whether the receiver is less than the argument."
    self notImplementedYet.

- <= aMagnitude
    "Answer whether the receiver is less than or equal to the argument."
    self notImplementedYet.

- > aMagnitude
    "Answer whether the receiver is greater than the argument."
    self notImplementedYet.

- >= aMagnitude
    "Answer whether the receiver is greater than or equal to the argument."
    self notImplementedYet.

- between: min and: max
    "Answer whether the receiver is greater than or equal to the argument, rain, and less than or equal to the argument,
     max."
    self notImplementedYet.

"category: testing"

- min: aMagnitude
    "Answer the receiver or the argument, whichever has the lesser magnitude."
    self notImplementedYet.

- max: aMagnitude
    "Answer the receiver or the argument, whichever has the greater magnitude."
    self notImplementedYet.
