"Redline Smalltalk, Copyright (c) James C. Ladd. All rights reserved. See LICENSE in the root of this distribution."

OrderedCollection subclass: #SortedCollection.

"category: instance creation"

- sortBlock: aBlock
    "Answer an instance of SortedCollection such that its elements will be sorted according to the criterion specified
     in the argument, aBlock."
    self notImplementedYet.

"category: accessing"

- sortBlock
    "Answer the block that is the criterion for sorting elements of the receiver."
    self notImplementedYet.

- sortBlock: aBlock
    "Make the argument, aBlock, be the criterion for ordering elements of the receiver."
    self notImplementedYet.
