"This is a comment"

Object subclass: #Test
	instanceVariableNames: 'events fiddlesticks'
	classVariableNames: 'DependentsFields'
	poolDictionaries: ''
	category: 'Kernel-Objects'!

!Test commentStamp: '<historical>' prior: 0!
this is a class level comment!

!Test methodsFor: 'as yet unclassified' stamp: 'gvc 9/22/2006 09:17'!
hatchForm
        "Answer a form showing a grid hatch pattern."

        ^nil! !

