Object subclass: #TryThis
	instanceVariableNames: 'instVar'
	classVariableNames: 'classVar'
	poolDictionaries: ''
	category: 'Kernel-Objects'!

!TryThis commentStamp: '<historical>' prior: 0!
stuff to try.!

!TryThis methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
placeholder
	"Answer."
        instVar := []
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

TryThis class
	instanceVariableNames: 'classInstVar'!

!TryThis class methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
classPlaceholder
	"Answer nil."
	classInstVar := nil

! !

