
Object subclass: #BlockWithAnswer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel-Block'!

!BlockWithAnswer commentStamp: '<historical>' prior: 0!
I represent a block of code that has an '^' answer statement.!

!BlockWithAnswer methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
placeholder
	"Answer nil."
	^ nil
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

BlockWithAnswer class
	instanceVariableNames: ''!

!BlockWithAnswer class methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
classPlaceholder
	"Answer nil."
	^ nil
! !
