"This is a placeholder to test bootstrapping"

Behavior subclass: #ClassDescription
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel-Objects'!

!ClassDescription commentStamp: '<historical>' prior: 0!
this is a class level comment!

!ClassDescription methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
placeholder
        "Answer nil."

        ^nil! !

