"This is a placeholder to test bootstrapping"

ProtoObject subclass: #Object
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel-Objects'!

!Object commentStamp: '<historical>' prior: 0!
this is a class level comment!

!Object methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
placeholder
        "Answer nil."

        ^nil! !

!Object class methodsFor: 'as yet unclassified' stamp: 'jcl 19/11/2010 09:17'!
classplaceholder
        "Answer nil."

        ^nil! !

